services:
  # NGINX container (TLSv1.2 and TLSv1.3 only)
  nginx:
    build:
      context: ./requirements/nginx  # Ruta de construcción desde la carpeta nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"  # Exponer puerto 443 para HTTPS
    volumes:
      - ./ssl:/etc/ssl/certs:ro  # Ruta para certificados SSL
      - ./requirements/wordpress:/var/www/html  # Enlace a los archivos de WordPress
    networks:
      - backend

  # WordPress container (with PHP-FPM)
  wordpress:
    build:
      context: ./requirements/wordpress  # Ruta de construcción desde la carpeta wordpress
    container_name: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306  # Conectar a MariaDB
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_pass
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html  # Enlace a los archivos de WordPress
    networks:
      - backend
    expose:
      - "9000"  # Exponer el puerto PHP-FPM internamente

  # MariaDB container
  db:
    build:
      context: ./requirements/mariadb  # Ruta de construcción desde la carpeta mariadb
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example  # Establecer la contraseña root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_pass
    volumes:
      - wordpress_db:/var/lib/mysql  # Enlace a la base de datos de WordPress
    networks:
      - backend

volumes:
  wordpress_data:  # Volumen para los archivos de WordPress
  wordpress_db:    # Volumen para la base de datos de MariaDB

networks:
  backend:
    driver: bridge  # Red personalizada para comunicación entre contenedores
