
services:
  mariadb:
    image: custom-mariadb
    container_name: mariadb
    env_file: ../.env
    volumes:
      - wp-db:/var/lib/mysql
    networks:
      - wpnet
    restart: always

  wordpress:
    image: custom-wordpress
    container_name: wordpress
    volumes:
      - wp-web:/var/www/html
    depends_on:
      - mariadb
    networks:
      - wpnet
    restart: always

  nginx:
    image: custom-nginx
    container_name: nginx
    volumes:
      - wp-web:/var/www/html
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - wpnet
    restart: always

volumes:
  wp-db:
    driver: local
    driver_opts:
      type: none
      device: /home/maikel/data/db
      o: bind

  wp-web:
    driver: local
    driver_opts:
      type: none
      device: /home/maikel/data/wp
      o: bind

networks:
  wpnet:
    driver: bridge
